version: '2'
services:
  tor:
    image: "zeta0/alpine-tor:latest"
    volumes:
      - /dev/shm:/dev/shm
    container_name: "nutch-crawler-tor"
    ports:
      - "8118:8118"
      - "2090:2090"
      - "5566:5566"
    environment:
      - tors=5
      - privoxy=1
  
  nutch:
    build: .
    container_name: "nutch-crawler-nutch"
    depends_on:
      - tor
      - mongo
    links:
      - tor
      - mongo
  
  mongo:
    image: mongo:latest
    container_name: "nutch-crawler-mongo"
    environment:
      - MONGO_INITDB_DATABASE=crawler
      - MONGO_INITDB_ROOT_USERNAME=crawler
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - db-data:/data/db

volumes:
  db-data:
    driver: local

